No.1 Membuat matriks dengan numpy

In [ ]:
import numpy as np

In [ ]:
matriks = np.array([[3,4,1],
                    [2,1,1],
                    [1,1,1]])
print(matriks)

[[3 4 1]
 [2 1 1]
 [1 1 1]]


No.2 Carilah inverse dari matriks tersebut

In [ ]:
matriks_inverse = np.linalg.inv(matriks)
matriks_inverse

array([[ 0.        ,  1.        , -1.        ],
       [ 0.33333333, -0.66666667,  0.33333333],
       [-0.33333333, -0.33333333,  1.66666667]])

No.3 Kalikan matriks tersebut dengan inversenya

In [ ]:
np.matmul(matriks,matriks_inverse)

array([[ 1.00000000e+00, -2.22044605e-16,  0.00000000e+00],
       [ 0.00000000e+00,  1.00000000e+00,  0.00000000e+00],
       [ 0.00000000e+00,  0.00000000e+00,  1.00000000e+00]])